using System;
using System.Windows.Forms;

namespace CalculatorApp
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();   // generated by Designer
        }

        private double ParseInput(TextBox txt)
        {
            return double.TryParse(txt.Text, out var val) ? val : 0;
        }

        // Event handlers
        private void btnAdd_Click(object sender, EventArgs e)
        {
            double a = ParseInput(txtA);
            double b = ParseInput(txtB);
            lblResult.Text = "Result = " + (a + b).ToString();
        }

        private void btnSub_Click(object sender, EventArgs e)
        {
            double a = ParseInput(txtA);
            double b = ParseInput(txtB);
            lblResult.Text = "Result = " + (a - b).ToString();
        }

        private void btnMul_Click(object sender, EventArgs e)
        {
            double a = ParseInput(txtA);
            double b = ParseInput(txtB);
            lblResult.Text = "Result = " + (a * b).ToString();
        }

        private void btnDiv_Click(object sender, EventArgs e)
        {
            double a = ParseInput(txtA);
            double b = ParseInput(txtB);
            lblResult.Text = (b == 0)
                ? "Result = ∞"
                : "Result = " + (a / b).ToString("0.###");
        }
    }
}
